# Site settings
title: Gabriele Lanaro
email: gabriele.lanaro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Gabriele Lanaro personal website. Science, Programming, Python, Technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gabrielelanaro.github.io" # the base hostname & protocol for your site
twitter_username: gabrielelanaro
github_username: gabrielelanaro

facebook: https://www.facebook.com/glanaro
googleplus: https://plus.google.com/+GabrieleLanaro
linkedin: https://www.linkedin.com/pub/gabriele-lanaro/61/901/666

# Build settings
markdown: kramdown
analytics: true
plugins:
  - jekyll-redirect-from

kramdown:
  input: GFM
  syntax_highlighter: rouge
